---
title: "tell your story with data"
author: "Jin Chen"
date: "9/19/2020"
output: html_document
---

```{r echo=FALSE}
library(tidyverse)
library(moderndive)
library(skimr)
library(fivethirtyeight)

```

```{r 11.2 Case study}
#EDA Part I - Univariate 
#1. Looking at the raw data values.
#2. Computing summary statistics.
#3. Creating data visualizations.

#1. Look at the raw data
View(house_prices)
glimpse(house_prices)


#2. Summary stats
house_prices %>% 
  select(price, sqft_living, condition) %>% 
  skim()


#3. Visualize - Histogram for numericals, bar for categorical
# Histogram of house price:
ggplot(house_prices, aes(x = price)) +
  geom_histogram(color = "white") +
  labs(x = "price (USD)", title = "House price")

# Histogram of sqft_living:
ggplot(house_prices, aes(x = sqft_living)) +
  geom_histogram(color = "white") +
  labs(x = "living space (square feet)", title = "House size")

# Barplot of condition:
ggplot(house_prices, aes(x = condition)) +
  geom_bar() +
  labs(x = "condition", title = "House condition")


#change to a log scale to account for outliers
house_prices <- house_prices %>%
  mutate(
    log10_price = log10(price),
    log10_size = log10(sqft_living)
    )

house_prices %>% 
  select(price, log10_price, sqft_living, log10_size)


# Before log10 transformation: for price
ggplot(house_prices, aes(x = price)) +
  geom_histogram(color = "white") +
  labs(x = "price (USD)", title = "House price: Before")

# After log10 transformation:
ggplot(house_prices, aes(x = log10_price)) +
  geom_histogram(color = "white") +
  labs(x = "log10 price (USD)", title = "House price: After")

# Before log10 transformation: for sqft
ggplot(house_prices, aes(x = sqft_living)) +
  geom_histogram(color = "white") +
  labs(x = "living space (square feet)", title = "House size: Before")

# After log10 transformation:
ggplot(house_prices, aes(x = log10_size)) +
  geom_histogram(color = "white") +
  labs(x = "log10 living space (square feet)", title = "House size: After")

```

```{r EDA Part II - Multivariate}
#with a numerical outcome variable, a numerical expla and categorical expla we have to choices of models. Interaction or parallel slopes

# Plot interaction model
ggplot(house_prices, 
       aes(x = log10_size, y = log10_price, col = condition)) +
  geom_point(alpha = 0.05) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(y = "log10 price", 
       x = "log10 size", 
       title = "House prices in Seattle")
# Plot parallel slopes model
ggplot(house_prices, 
       aes(x = log10_size, y = log10_price, col = condition)) +
  geom_point(alpha = 0.05) +
  geom_parallel_slopes(se = FALSE) +
  labs(y = "log10 price", 
       x = "log10 size", 
       title = "House prices in Seattle")

#Facet
ggplot(house_prices, 
       aes(x = log10_size, y = log10_price, col = condition)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(y = "log10 price", 
       x = "log10 size", 
       title = "House prices in Seattle") +
  facet_wrap(~ condition)


```

```{r Regression Modelling}
# Fit regression model:
price_interaction <- lm(log10_price ~ log10_size * condition, 
                        data = house_prices)

# Get regression table:
get_regression_table(price_interaction) 
#intercept and log10_size are the baseline for comparison using condition 1 houses


#what is the prediction for condition 5 house of size 1900 sqft?
2.45 + 1 * log10(1900)
10^(2.45 + 1 * log10(1900)) #unlog to find price

```


```{r}
#use a parallel slopes model to predict the same house of condition 5 and size 1900 sqft
#in parallel slopes model, we use + instead of * in the regression syntax
price_interaction2 <- lm(log10_price ~ log10_size + condition,
                         data = house_prices)
get_regression_table(price_interaction2)

#get price
10^((2.882 + 0.096) + (0.837 * log10(1900)))
10^(2.88 + 0.096 + 0.837 * log10(1900))
```


```{r 11.3 Case study:effective data storytelling}
#look at raw data
glimpse(US_births_1994_2003)

US_births_1999 <- US_births_1994_2003 %>%
  filter(year == 1999)

ggplot(US_births_1999, aes(x = date, y = births)) +
  geom_line() +
  labs(x = "Date", 
       y = "Number of births", 
       title = "US Births in 1999")

US_births_1999 %>% 
  arrange(desc(births))

US_births_1999 %>% 
  arrange(births)

```

