---
title: "hypothesis testing"
author: "Jin Chen"
date: "9/17/2020"
output: html_document
---

```{r}
library(tidyverse)
library(infer)
library(moderndive)
library(nycflights13)
library(ggplot2movies)
```

```{r}
promotions %>% 
  sample_n(size = 6) %>% 
  arrange(id)

ggplot(promotions, aes(x = gender, fill = decision)) +
  geom_bar() +
  labs(x = "Gender of name on résumé")

promotions %>% 
  group_by(gender, decision) %>% 
  tally()

ggplot(promotions_shuffled, 
       aes(x = gender, fill = decision)) +
  geom_bar() + 
  labs(x = "Gender of résumé name")

promotions_shuffled %>% 
  group_by(gender, decision) %>% 
  tally() # Same as summarize(n = n())

```

```{r 9.3 Conducting hypothesis tests}
promotions_generate <- promotions %>% 
  specify(formula = decision ~ gender, success = "promoted") %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 1000, type = "permute")
nrow(promotions_generate)

#create the null distribution for the null hypothesis
null_distribution <- promotions %>% 
  specify(formula = decision ~ gender, success = "promoted") %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in props", order = c("male", "female"))
null_distribution

#calculate the observed test statistic
obs_diff_prop <- promotions %>% 
  specify(decision ~ gender, success = "promoted") %>% 
  calculate(stat = "diff in props", order = c("male", "female"))
obs_diff_prop

#visualize the null distribution
visualize(null_distribution, bins = 10) +
  shade_p_value(obs_stat = obs_diff_prop, direction = "right")

#what is the fraction of the null distribution shaded by the observed test stat?
null_distribution %>% 
  get_p_value(obs_stat = obs_diff_prop, direction = "right")

#if we consider a significance level of 0.05, and the p-value is 0.024. We reject the null hypothesis. There is a 2.7% chance that if the null hypothesis is true, the difference in observed promotion rates is as large as 29.2%.

#infer package allows a quick switch to the boostrap method
bootstrap_distribution <- promotions %>% 
  specify(formula = decision ~ gender, success = "promoted") %>% 
  # Change 1 - Remove hypothesize():
  # hypothesize(null = "independence") %>% 
  # Change 2 - Switch type from "permute" to "bootstrap":
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "diff in props", order = c("male", "female"))

percentile_ci <- bootstrap_distribution %>% 
  get_confidence_interval(level = 0.95, type = "percentile")
percentile_ci

visualize(bootstrap_distribution) + 
  shade_confidence_interval(endpoints = percentile_ci) #here, a difference of 0 is not included in the CI, suggesting that the test statistic are truly different


#using standard error method
se_ci <- bootstrap_distribution %>% 
  get_confidence_interval(level = 0.95, type = "se", 
                          point_estimate = obs_diff_prop)
se_ci

visualize(bootstrap_distribution) + 
  shade_confidence_interval(endpoints = se_ci)
```

```{r 9.5 Case study}
#boxplot to explore numerical vs. categorical variables
ggplot(data = movies_sample, aes(x = genre, y = rating)) +
  geom_boxplot() +
  labs(y = "IMDb rating")


movies_sample %>% 
  group_by(genre) %>% 
  summarize(n = n(), mean_rating = mean(rating), std_dev = sd(rating)) #difference of 5.275 - 6.322 = -1.047 in mean rating. Is this truly indicative of a difference in all romance and action movies or is this a difference to chance sampling variation?


#we set significance level to 0.001, a conservative test
null_distribution_movies <- movies_sample %>% 
  specify(formula = rating ~ genre) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c("Action", "Romance"))
null_distribution_movies
  
obs_diff_means <- movies_sample %>% 
  specify(formula = rating ~ genre) %>% 
  calculate(stat = "diff in means", order = c("Action", "Romance"))
obs_diff_means

visualize(null_distribution_movies, bins = 10) + 
  shade_p_value(obs_stat = obs_diff_means, direction = "both")

#what proportion of the null distribution is shaded? In other words, what is the p-value?
null_distribution_movies %>% 
  get_p_value(obs_stat = obs_diff_means, direction = "both")

#we fail to reject the null hypothesis because 0.01 is greater than 0.001. Thus, we do not have evidence to suggest that we should reject the hypothesis that there is no difference in mean IMDb ratings between romance and action movies. Thus, we cannot say a difference exists in romance and action movie ratings, on average, for all IMDb movies.

```
```{r Conclusion}
flights_sample <- flights %>% 
  filter(carrier %in% c("HA", "AS"))

#EDA - "no PhD in statistics needed!"
ggplot(data = flights_sample, mapping = aes(x = carrier, y = air_time)) +
  geom_boxplot() +
  labs(x = "Carrier", y = "Air Time")


flights_sample %>% 
  group_by(carrier, dest) %>% 
  summarize(n = n(), mean_time = mean(air_time, na.rm = TRUE))

```

